### ISSUE TITLE
Is there any doc about how to run this benchmark?

### ISSUE THREAD

**Issue by jesusjzp** [ning/jvm-compressor-benchmark#11]
Hi there,

I'm new here, I'd like to know is there any guide or doc about how to run this benchmark? I have checked the wiki and also japex's documentation, but I didn't find any clue.

Thanks!
Zhipeng

**Comment by cowtowncoder** [comment]
Good question -- I need to add something on README as that is an obvious question.

Main directory of the project contains (Unix) scripts like `run-lzf-compress.sh` which shows how to invoke tests. Configuration is with xml files, referred to by the script. You can invoke scripts as-is, or, more likely, modify with respect to parameters or configuration file.

This is not a very good way to run tests, but is how it's done currently.

**Comment by jesusjzp** [comment]
Thanks @cowtowncoder !

I tried `run-lzf-compress.sh` directly in the root directory, but got the error below:

```shell
About to run Compress test for LZF impls on Calgary corpus files
Reading configuration file 'cfg/tests-lzf-compress.xml' ...
374 [main] ERROR com.sun.japex.Engine - Error: Unable to load any of the drivers in the test suite
Exception in thread "main" com.sun.japex.JapexException: com.sun.japex.JapexException: com.sun.japex.JapexException: Error: Unable to load any of the drivers in the test suite
	at com.sun.japex.Engine.start(Engine.java:183)
	at com.sun.japex.Japex.run(Japex.java:175)
	at com.sun.japex.Japex.main(Japex.java:147)
Caused by: com.sun.japex.JapexException: com.sun.japex.JapexException: Error: Unable to load any of the drivers in the test suite
	at com.sun.japex.Engine.forEachDriver(Engine.java:332)
	at com.sun.japex.Engine.start(Engine.java:180)
	... 2 more
Caused by: com.sun.japex.JapexException: Error: Unable to load any of the drivers in the test suite
	at com.sun.japex.Engine.forEachDriver(Engine.java:327)
	... 3 more
Done!
```
Did I miss anything? Or should build some packages before run this script? Thanks!

**Comment by cowtowncoder** [comment]
Correct: you do need to do `mvn install` first: script assumes existence of built jar(s).

**Comment by jesusjzp** [comment]
Hi @cowtowncoder, I used `ant compile` to compile source code and now it's running. Thank you for your help!

**Comment by cowtowncoder** [comment]
Ah sorry for bad advice above -- I forgot it still had ant build, not maven.

**Comment by cowtowncoder** [comment]
FWTW, I am converting build to Maven now. May try to use `jmh` for benchmarking part but if so need to figure how to merge compression ratio information with performance numbers.
